fpath = './test/'
action_mmap = memmapfile( ...
    [fpath 'action.mmap'], ...
    'Format', 'uint8' ...
    );
event_mmap = memmapfile( ...
    [fpath 'event.mmap'], ...
    'Format', 'uint8' ...
    );
flag_mmap = memmapfile( ...
    [fpath 'flag.mmap'], ...
    'Format', 'uint8', ...
    );
position_mmap = memmapfile( ...
    [fpath 'position.mmap'], ...
    'Format', {'uint8', 
